name: py39
channels:
  - defaults
  - conda-forge
dependencies:
  - boto3
  - cartopy
  - dask
  - gdal
  - geopandas
  - holoviews
  - hvplot
  - geoviews
  - matplotlib
  - numpy
  - pandas
  - pystac-client
  - python=3.9
  - rasterio
  - rioxarray
  - shapely
  - stackstac=0.2.1
  - xarray
  - zarr
  - nbgitpuller==0.9.0
  - jupyterlab-geojson==3.1.2
